language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

dist: bionic

addons:
  apt:
    packages:
    - gfortran
    - libatlas-base-dev
    - liblapack-dev
    - libgmp-dev
    - libmpfr-dev
    - graphviz
    - libglpk-dev
    - libboost-dev
    - libboost-filesystem-dev
    - libboost-program-options-dev
    - libboost-regex-dev
    - libboost-test-dev
    - libeigen3-dev
    - z3
    - libz3-dev
    - python-z3
    - libhwloc-dev

before_install:
  - pip install --ignore-installed --upgrade pip setuptools wheel
  - pip install --upgrade --only-binary=numpy,scipy numpy scipy
  - if test 2 = `python -c 'import sys; print(sys.version_info.major)'`; then pip install networkx==2.2; fi
  - pip install dd --no-binary dd

install:
  - python setup.py sdist
  - pip install dist/tulip-*.tar.gz

before_script:
  - pip install nose
  - dot -V

script:
  - ./run_tests.py --outofsource base
  - pip install matplotlib
  - ./run_tests.py --outofsource --fast hybrid
  # install cvxopt.glpk
  - export CVXOPT_BUILD_GLPK=1
  - python -c "import setup; setup.install_cvxopt()"
  - python -c "import cvxopt.glpk"
  # install `dd.cudd`
  - pip uninstall --yes dd
  - pip download --no-dependencies dd --no-binary dd
  - tar xzf dd-*.tar.gz
  - cd dd-*/
  - export CUDD_VERSION=3.0.0
  - export CUDD_GZ=cudd-${CUDD_VERSION}.tar.gz
  - curl -sSL https://sourceforge.net/projects/cudd-mirror/files/${CUDD_GZ}/download > ${CUDD_GZ}
  - expr `shasum -a 256 ${CUDD_GZ}|cut -d ' ' -f1`
    = b8e966b4562c96a03e7fbea239729587d7b395d53cadcc39a7203b49cf7eeb69
  - tar -xzf ${CUDD_GZ}
  - python -c 'from download import make_cudd; make_cudd()'
  - python setup.py install --cudd
  - cd ..
  # optional python packages
  - pip install gr1py
  # gr1c
  - export GR1CVERSION=0.11.0
  - curl -sSLO https://dl.bintray.com/slivingston/generic/gr1c-${GR1CVERSION}-Linux_x86-64.tar.gz
  - expr `shasum -a 256 gr1c-${GR1CVERSION}-Linux_x86-64.tar.gz|cut -d ' ' -f1`
    = 563cc531bb034687c1d184b5d0da95e9f2b5699958912453894b53383cd0a298
  - tar -xzf gr1c-${GR1CVERSION}-Linux_x86-64.tar.gz
  - export PATH=`pwd`/gr1c-${GR1CVERSION}-Linux_x86-64:$PATH
  # lily
  - ./extern/get-lily.sh
  - which perl
  - perl --version
  - pwd
  - export PERL5LIB=`pwd`/Lily-1.0.2
  - export PATH=`pwd`/Lily-1.0.2:$PATH
  - echo $PATH
  - which lily.pl
  # slugs
  - ./extern/get-slugs.sh
  - export PATH=`pwd`/slugs-repo/src:$PATH
  - which slugs
  # dev test requirements
  - pip install gitpython
  - pip install mock
  # stormpy, requires Python 3
  - if test 3 = `python -c 'import sys; print(sys.version_info.major)'`; then ./extern/get-stormpy.sh; fi
  # all tests, including slow hybrid and alternative game solvers
  - ./run_tests.py --outofsource full

notifications:
  email: false
